# Generated by Django 5.0.6 on 2024-05-14 07:36

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(default=home.models.default_address, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(default=home.models.default_email, max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(default=home.models.default_phone_number, max_length=15),
        ),
        migrations.AddField(
            model_name='service',
            name='pincode',
            field=models.CharField(default=home.models.default_pincode, max_length=10),
        ),
    ]
